version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "deps: "
    labels:
      - "dependabot"
